// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAai9PSZ5ZVdoglpRu9aPc2BWviA61ZPuU',
    appId: '1:803748068384:web:33e5055a65ccc7258c9045',
    messagingSenderId: '803748068384',
    projectId: 'tcc-procurapet',
    authDomain: 'tcc-procurapet.firebaseapp.com',
    storageBucket: 'tcc-procurapet.firebasestorage.app',
    measurementId: 'G-NH84HW926J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPxyQLyKnxpkv9v51PiCj5SmonVke2hc',
    appId: '1:803748068384:android:75f19697a3d25bdf8c9045',
    messagingSenderId: '803748068384',
    projectId: 'tcc-procurapet',
    storageBucket: 'tcc-procurapet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGt7WBB6xALdoXeQT541zh4mZngCA8kg0',
    appId: '1:803748068384:ios:25ce62362dc24e4c8c9045',
    messagingSenderId: '803748068384',
    projectId: 'tcc-procurapet',
    storageBucket: 'tcc-procurapet.firebasestorage.app',
    iosBundleId: 'com.example.tccProcurapet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGt7WBB6xALdoXeQT541zh4mZngCA8kg0',
    appId: '1:803748068384:ios:25ce62362dc24e4c8c9045',
    messagingSenderId: '803748068384',
    projectId: 'tcc-procurapet',
    storageBucket: 'tcc-procurapet.firebasestorage.app',
    iosBundleId: 'com.example.tccProcurapet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAai9PSZ5ZVdoglpRu9aPc2BWviA61ZPuU',
    appId: '1:803748068384:web:6a05a5b2fbd6434d8c9045',
    messagingSenderId: '803748068384',
    projectId: 'tcc-procurapet',
    authDomain: 'tcc-procurapet.firebaseapp.com',
    storageBucket: 'tcc-procurapet.firebasestorage.app',
    measurementId: 'G-YBMW1E8K7Y',
  );
}
